cache: apt

language: go
go:
  - tip
  - 1.6.2
  - 1.6.1
  - 1.6  
  - 1.5.2
  - 1.5.1
  - 1.5
  
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -coverprofile=bqstreamer.coverprofile ./

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
