language: go
go:
  - tip
  - 1.6.2
  - 1.6.1
  - 1.6  
  - 1.5.2
  - 1.5.1
  - 1.5
  
before_install:
  - go get golang.org/x/tools/cmd/cover

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
